/** Panel accent tokens — bright sky-blue admin & super admin themes. */

export const ADMIN_THEME = {
  id: "admin",
  label: "Admin",
  loginTitle: "Admin Portal",
  loginSubtitle: "Operations dashboard for platform admins",
  pageBg: "bg-gradient-to-br from-sky-50 via-white to-teal-50/40",
  loginPageBg: "bg-gradient-to-br from-sky-50 via-white to-cyan-50",
  cardBorder: "border-sky-200",
  cardGlow: "shadow-sky-100/60",
  primary:
    "bg-gradient-to-r from-sky-500 to-cyan-500 hover:from-sky-400 hover:to-cyan-400 shadow-lg shadow-sky-200/50",
  primarySolid: "bg-sky-500 hover:bg-sky-600",
  primaryRing: "focus:ring-sky-500 border-sky-400",
  accentText: "text-sky-600",
  accentTextMuted: "text-cyan-600",
  mutedText: "text-slate-500",
  headingText: "text-slate-900",
  sidebar: "from-sky-50 via-white to-cyan-50/70 border-sky-200",
  sidebarLabel: "text-sky-500",
  navActive: "from-sky-500 to-cyan-500 shadow-sky-200/50",
  navIdle: "text-sky-900/80 hover:bg-sky-50",
  navIconBg: "bg-sky-100 group-hover:bg-sky-200/80",
  navIcon: "text-sky-600",
  topBar: "border-sky-100 bg-white/95",
  topBarSubtext: "text-sky-600/80",
  chip: "bg-sky-100 text-sky-800",
  fab: "from-sky-500 to-cyan-500",
  badge: "bg-sky-500",
  badgeActive: "bg-white text-sky-700",
  avatarGradient: "from-sky-400 to-cyan-500",
  avatarBorder: "border-sky-200",
  iconButton: "bg-sky-50 hover:bg-sky-100",
  iconButtonText: "text-sky-600",
  dropdown: "bg-white border border-sky-100",
  dropdownBorder: "border-sky-100",
  dropdownText: "text-slate-900",
  dropdownMuted: "text-sky-600",
  dropdownHover: "hover:bg-sky-50",
  portalCard:
    "border-2 border-sky-200 bg-white hover:border-sky-400 shadow-lg hover:shadow-sky-100",
  portalIconBg: "bg-sky-100",
  portalIcon: "text-sky-600",
  loginCard: "bg-white shadow-xl border-sky-100",
  inputRing: "focus:ring-sky-500 focus:border-sky-500",
};

export const SUPER_ADMIN_THEME = {
  id: "super_admin",
  label: "Super Admin",
  loginTitle: "Super Admin Command",
  loginSubtitle: "Full platform control & admin team management",
  pageBg: "bg-gradient-to-br from-sky-100 via-white to-blue-50",
  loginPageBg: "bg-gradient-to-br from-sky-100 via-white to-cyan-50",
  cardBorder: "border-sky-300/60",
  cardGlow: "shadow-sky-200/50 shadow-xl",
  primary:
    "bg-gradient-to-r from-sky-500 via-blue-500 to-cyan-500 hover:from-sky-400 hover:via-blue-400 hover:to-cyan-400 shadow-lg shadow-sky-300/40",
  primarySolid: "bg-blue-500 hover:bg-blue-600",
  primaryRing: "focus:ring-sky-500 border-sky-400",
  accentText: "text-blue-600",
  accentTextMuted: "text-sky-600",
  mutedText: "text-slate-500",
  headingText: "text-slate-900",
  sidebar: "from-sky-100 via-white to-cyan-50 border-sky-200",
  sidebarLabel: "text-blue-500",
  navActive: "from-sky-500 via-blue-500 to-cyan-500 shadow-sky-300/40",
  navIdle: "text-slate-700 hover:bg-sky-50",
  navIconBg: "bg-sky-100 group-hover:bg-sky-200",
  navIcon: "text-blue-600",
  topBar: "border-sky-200 bg-white/95",
  topBarSubtext: "text-sky-600",
  chip: "bg-sky-100 text-blue-800 border border-sky-200",
  fab: "from-sky-500 to-cyan-500",
  badge: "bg-blue-500",
  badgeActive: "bg-white text-blue-700",
  avatarGradient: "from-sky-400 via-blue-500 to-cyan-500",
  avatarBorder: "border-sky-300",
  iconButton: "bg-sky-50 hover:bg-sky-100",
  iconButtonText: "text-blue-600",
  dropdown: "bg-white border border-sky-200 shadow-xl",
  dropdownBorder: "border-sky-100",
  dropdownText: "text-slate-900",
  dropdownMuted: "text-sky-600",
  dropdownHover: "hover:bg-sky-50",
  portalCard:
    "border-2 border-sky-300 bg-gradient-to-br from-sky-50 via-white to-cyan-50 shadow-xl shadow-sky-200/60 hover:scale-[1.02] hover:border-blue-400",
  portalIconBg: "bg-sky-100 border border-sky-200",
  portalIcon: "text-blue-600",
  loginCard: "bg-white shadow-2xl border-sky-200",
  inputRing: "focus:ring-sky-500 border-sky-200 text-slate-900 placeholder:text-slate-400",
};

export function getTheme(isSuperAdmin) {
  return isSuperAdmin ? SUPER_ADMIN_THEME : ADMIN_THEME;
}
